// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: dya/analog_input/analog_input.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "dya.analog_input";

export const AnalogRole = {
  ANALOG_ROLE_REL_X: 0,
  ANALOG_ROLE_REL_Y: 1,
  ANALOG_ROLE_REL_WHEEL: 2,
  ANALOG_ROLE_REL_HWHEEL: 3,
  ANALOG_ROLE_ABS_X: 4,
  ANALOG_ROLE_ABS_Y: 5,
  UNRECOGNIZED: -1,
} as const;

export type AnalogRole = typeof AnalogRole[keyof typeof AnalogRole];

export namespace AnalogRole {
  export type ANALOG_ROLE_REL_X = typeof AnalogRole.ANALOG_ROLE_REL_X;
  export type ANALOG_ROLE_REL_Y = typeof AnalogRole.ANALOG_ROLE_REL_Y;
  export type ANALOG_ROLE_REL_WHEEL = typeof AnalogRole.ANALOG_ROLE_REL_WHEEL;
  export type ANALOG_ROLE_REL_HWHEEL = typeof AnalogRole.ANALOG_ROLE_REL_HWHEEL;
  export type ANALOG_ROLE_ABS_X = typeof AnalogRole.ANALOG_ROLE_ABS_X;
  export type ANALOG_ROLE_ABS_Y = typeof AnalogRole.ANALOG_ROLE_ABS_Y;
  export type UNRECOGNIZED = typeof AnalogRole.UNRECOGNIZED;
}

export const AnalogResponseCurve = {
  ANALOG_RESPONSE_CURVE_LINEAR: 0,
  ANALOG_RESPONSE_CURVE_SOFT: 1,
  ANALOG_RESPONSE_CURVE_AGGRESSIVE: 2,
  UNRECOGNIZED: -1,
} as const;

export type AnalogResponseCurve = typeof AnalogResponseCurve[keyof typeof AnalogResponseCurve];

export namespace AnalogResponseCurve {
  export type ANALOG_RESPONSE_CURVE_LINEAR = typeof AnalogResponseCurve.ANALOG_RESPONSE_CURVE_LINEAR;
  export type ANALOG_RESPONSE_CURVE_SOFT = typeof AnalogResponseCurve.ANALOG_RESPONSE_CURVE_SOFT;
  export type ANALOG_RESPONSE_CURVE_AGGRESSIVE = typeof AnalogResponseCurve.ANALOG_RESPONSE_CURVE_AGGRESSIVE;
  export type UNRECOGNIZED = typeof AnalogResponseCurve.UNRECOGNIZED;
}

export interface AnalogAxisConfig {
  axisIndex: number;
  name: string;
  enabled: boolean;
  adcChannel: number;
  mvMid: number;
  mvMinMax: number;
  mvDeadzone: number;
  scaleMultiplier: number;
  scaleDivisor: number;
  invert: boolean;
  role: AnalogRole;
  reportOnChangeOnly: boolean;
  outputMin: number;
  outputMax: number;
  responseCurve: AnalogResponseCurve;
}

export interface AnalogInputDevice {
  id: number;
  name: string;
  samplingHz: number;
  reportIntervalMs: number;
  axes: AnalogAxisConfig[];
}

export interface ListDevicesRequest {
}

export interface ListDevicesResponse {
  devices: AnalogInputDevice[];
}

export interface GetDeviceRequest {
  id: number;
}

export interface GetDeviceResponse {
  device: AnalogInputDevice | undefined;
}

export interface SetSamplingHzRequest {
  id: number;
  value: number;
}

export interface SetSamplingHzResponse {
}

export interface SetReportIntervalRequest {
  id: number;
  valueMs: number;
}

export interface SetReportIntervalResponse {
}

export interface SetAxisConfigRequest {
  deviceId: number;
  axis: AnalogAxisConfig | undefined;
}

export interface SetAxisConfigResponse {
}

export interface ResetDeviceRequest {
  id: number;
}

export interface ResetDeviceResponse {
}

export interface AnalogAxisValue {
  axisIndex: number;
  adcChannel: number;
  raw: number;
  mv: number;
  reportValue: number;
  accumulatedDelta: number;
}

export interface GetValuesRequest {
  id: number;
}

export interface GetValuesResponse {
  values: AnalogAxisValue[];
  sampledAtMs: number;
}

export interface ErrorResponse {
  message: string;
}

export interface Request {
  listDevices?: ListDevicesRequest | undefined;
  getDevice?: GetDeviceRequest | undefined;
  setSamplingHz?: SetSamplingHzRequest | undefined;
  setReportInterval?: SetReportIntervalRequest | undefined;
  setAxisConfig?: SetAxisConfigRequest | undefined;
  resetDevice?: ResetDeviceRequest | undefined;
  getValues?: GetValuesRequest | undefined;
}

export interface Response {
  error?: ErrorResponse | undefined;
  listDevices?: ListDevicesResponse | undefined;
  getDevice?: GetDeviceResponse | undefined;
  setSamplingHz?: SetSamplingHzResponse | undefined;
  setReportInterval?: SetReportIntervalResponse | undefined;
  setAxisConfig?: SetAxisConfigResponse | undefined;
  resetDevice?: ResetDeviceResponse | undefined;
  getValues?: GetValuesResponse | undefined;
}

export interface DeviceChangedNotification {
  device: AnalogInputDevice | undefined;
}

export interface Notification {
  deviceChanged?: DeviceChangedNotification | undefined;
}

function createBaseAnalogAxisConfig(): AnalogAxisConfig {
  return {
    axisIndex: 0,
    name: "",
    enabled: false,
    adcChannel: 0,
    mvMid: 0,
    mvMinMax: 0,
    mvDeadzone: 0,
    scaleMultiplier: 0,
    scaleDivisor: 0,
    invert: false,
    role: 0,
    reportOnChangeOnly: false,
    outputMin: 0,
    outputMax: 0,
    responseCurve: 0,
  };
}

export const AnalogAxisConfig: MessageFns<AnalogAxisConfig> = {
  encode(message: AnalogAxisConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.axisIndex !== 0) {
      writer.uint32(8).uint32(message.axisIndex);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.enabled !== false) {
      writer.uint32(24).bool(message.enabled);
    }
    if (message.adcChannel !== 0) {
      writer.uint32(32).uint32(message.adcChannel);
    }
    if (message.mvMid !== 0) {
      writer.uint32(40).uint32(message.mvMid);
    }
    if (message.mvMinMax !== 0) {
      writer.uint32(48).uint32(message.mvMinMax);
    }
    if (message.mvDeadzone !== 0) {
      writer.uint32(56).uint32(message.mvDeadzone);
    }
    if (message.scaleMultiplier !== 0) {
      writer.uint32(64).uint32(message.scaleMultiplier);
    }
    if (message.scaleDivisor !== 0) {
      writer.uint32(72).uint32(message.scaleDivisor);
    }
    if (message.invert !== false) {
      writer.uint32(80).bool(message.invert);
    }
    if (message.role !== 0) {
      writer.uint32(88).int32(message.role);
    }
    if (message.reportOnChangeOnly !== false) {
      writer.uint32(96).bool(message.reportOnChangeOnly);
    }
    if (message.outputMin !== 0) {
      writer.uint32(104).uint32(message.outputMin);
    }
    if (message.outputMax !== 0) {
      writer.uint32(112).uint32(message.outputMax);
    }
    if (message.responseCurve !== 0) {
      writer.uint32(120).int32(message.responseCurve);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnalogAxisConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnalogAxisConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.axisIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.adcChannel = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.mvMid = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.mvMinMax = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.mvDeadzone = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.scaleMultiplier = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.scaleDivisor = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.invert = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.reportOnChangeOnly = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.outputMin = reader.uint32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.outputMax = reader.uint32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.responseCurve = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AnalogAxisConfig>): AnalogAxisConfig {
    return AnalogAxisConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AnalogAxisConfig>): AnalogAxisConfig {
    const message = createBaseAnalogAxisConfig();
    message.axisIndex = object.axisIndex ?? 0;
    message.name = object.name ?? "";
    message.enabled = object.enabled ?? false;
    message.adcChannel = object.adcChannel ?? 0;
    message.mvMid = object.mvMid ?? 0;
    message.mvMinMax = object.mvMinMax ?? 0;
    message.mvDeadzone = object.mvDeadzone ?? 0;
    message.scaleMultiplier = object.scaleMultiplier ?? 0;
    message.scaleDivisor = object.scaleDivisor ?? 0;
    message.invert = object.invert ?? false;
    message.role = object.role ?? 0;
    message.reportOnChangeOnly = object.reportOnChangeOnly ?? false;
    message.outputMin = object.outputMin ?? 0;
    message.outputMax = object.outputMax ?? 0;
    message.responseCurve = object.responseCurve ?? 0;
    return message;
  },
};

function createBaseAnalogInputDevice(): AnalogInputDevice {
  return { id: 0, name: "", samplingHz: 0, reportIntervalMs: 0, axes: [] };
}

export const AnalogInputDevice: MessageFns<AnalogInputDevice> = {
  encode(message: AnalogInputDevice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.samplingHz !== 0) {
      writer.uint32(24).uint32(message.samplingHz);
    }
    if (message.reportIntervalMs !== 0) {
      writer.uint32(32).uint32(message.reportIntervalMs);
    }
    for (const v of message.axes) {
      AnalogAxisConfig.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnalogInputDevice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnalogInputDevice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.samplingHz = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.reportIntervalMs = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.axes.push(AnalogAxisConfig.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AnalogInputDevice>): AnalogInputDevice {
    return AnalogInputDevice.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AnalogInputDevice>): AnalogInputDevice {
    const message = createBaseAnalogInputDevice();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.samplingHz = object.samplingHz ?? 0;
    message.reportIntervalMs = object.reportIntervalMs ?? 0;
    message.axes = object.axes?.map((e) => AnalogAxisConfig.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListDevicesRequest(): ListDevicesRequest {
  return {};
}

export const ListDevicesRequest: MessageFns<ListDevicesRequest> = {
  encode(_: ListDevicesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListDevicesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDevicesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListDevicesRequest>): ListDevicesRequest {
    return ListDevicesRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListDevicesRequest>): ListDevicesRequest {
    const message = createBaseListDevicesRequest();
    return message;
  },
};

function createBaseListDevicesResponse(): ListDevicesResponse {
  return { devices: [] };
}

export const ListDevicesResponse: MessageFns<ListDevicesResponse> = {
  encode(message: ListDevicesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.devices) {
      AnalogInputDevice.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListDevicesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDevicesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.devices.push(AnalogInputDevice.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListDevicesResponse>): ListDevicesResponse {
    return ListDevicesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListDevicesResponse>): ListDevicesResponse {
    const message = createBaseListDevicesResponse();
    message.devices = object.devices?.map((e) => AnalogInputDevice.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetDeviceRequest(): GetDeviceRequest {
  return { id: 0 };
}

export const GetDeviceRequest: MessageFns<GetDeviceRequest> = {
  encode(message: GetDeviceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDeviceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDeviceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetDeviceRequest>): GetDeviceRequest {
    return GetDeviceRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDeviceRequest>): GetDeviceRequest {
    const message = createBaseGetDeviceRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseGetDeviceResponse(): GetDeviceResponse {
  return { device: undefined };
}

export const GetDeviceResponse: MessageFns<GetDeviceResponse> = {
  encode(message: GetDeviceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.device !== undefined) {
      AnalogInputDevice.encode(message.device, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDeviceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDeviceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.device = AnalogInputDevice.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetDeviceResponse>): GetDeviceResponse {
    return GetDeviceResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDeviceResponse>): GetDeviceResponse {
    const message = createBaseGetDeviceResponse();
    message.device = (object.device !== undefined && object.device !== null)
      ? AnalogInputDevice.fromPartial(object.device)
      : undefined;
    return message;
  },
};

function createBaseSetSamplingHzRequest(): SetSamplingHzRequest {
  return { id: 0, value: 0 };
}

export const SetSamplingHzRequest: MessageFns<SetSamplingHzRequest> = {
  encode(message: SetSamplingHzRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.value !== 0) {
      writer.uint32(16).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetSamplingHzRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSamplingHzRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetSamplingHzRequest>): SetSamplingHzRequest {
    return SetSamplingHzRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetSamplingHzRequest>): SetSamplingHzRequest {
    const message = createBaseSetSamplingHzRequest();
    message.id = object.id ?? 0;
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseSetSamplingHzResponse(): SetSamplingHzResponse {
  return {};
}

export const SetSamplingHzResponse: MessageFns<SetSamplingHzResponse> = {
  encode(_: SetSamplingHzResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetSamplingHzResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSamplingHzResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetSamplingHzResponse>): SetSamplingHzResponse {
    return SetSamplingHzResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SetSamplingHzResponse>): SetSamplingHzResponse {
    const message = createBaseSetSamplingHzResponse();
    return message;
  },
};

function createBaseSetReportIntervalRequest(): SetReportIntervalRequest {
  return { id: 0, valueMs: 0 };
}

export const SetReportIntervalRequest: MessageFns<SetReportIntervalRequest> = {
  encode(message: SetReportIntervalRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.valueMs !== 0) {
      writer.uint32(16).uint32(message.valueMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetReportIntervalRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetReportIntervalRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.valueMs = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetReportIntervalRequest>): SetReportIntervalRequest {
    return SetReportIntervalRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetReportIntervalRequest>): SetReportIntervalRequest {
    const message = createBaseSetReportIntervalRequest();
    message.id = object.id ?? 0;
    message.valueMs = object.valueMs ?? 0;
    return message;
  },
};

function createBaseSetReportIntervalResponse(): SetReportIntervalResponse {
  return {};
}

export const SetReportIntervalResponse: MessageFns<SetReportIntervalResponse> = {
  encode(_: SetReportIntervalResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetReportIntervalResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetReportIntervalResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetReportIntervalResponse>): SetReportIntervalResponse {
    return SetReportIntervalResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SetReportIntervalResponse>): SetReportIntervalResponse {
    const message = createBaseSetReportIntervalResponse();
    return message;
  },
};

function createBaseSetAxisConfigRequest(): SetAxisConfigRequest {
  return { deviceId: 0, axis: undefined };
}

export const SetAxisConfigRequest: MessageFns<SetAxisConfigRequest> = {
  encode(message: SetAxisConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceId !== 0) {
      writer.uint32(8).uint32(message.deviceId);
    }
    if (message.axis !== undefined) {
      AnalogAxisConfig.encode(message.axis, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetAxisConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetAxisConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.deviceId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.axis = AnalogAxisConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetAxisConfigRequest>): SetAxisConfigRequest {
    return SetAxisConfigRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetAxisConfigRequest>): SetAxisConfigRequest {
    const message = createBaseSetAxisConfigRequest();
    message.deviceId = object.deviceId ?? 0;
    message.axis = (object.axis !== undefined && object.axis !== null)
      ? AnalogAxisConfig.fromPartial(object.axis)
      : undefined;
    return message;
  },
};

function createBaseSetAxisConfigResponse(): SetAxisConfigResponse {
  return {};
}

export const SetAxisConfigResponse: MessageFns<SetAxisConfigResponse> = {
  encode(_: SetAxisConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetAxisConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetAxisConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetAxisConfigResponse>): SetAxisConfigResponse {
    return SetAxisConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SetAxisConfigResponse>): SetAxisConfigResponse {
    const message = createBaseSetAxisConfigResponse();
    return message;
  },
};

function createBaseResetDeviceRequest(): ResetDeviceRequest {
  return { id: 0 };
}

export const ResetDeviceRequest: MessageFns<ResetDeviceRequest> = {
  encode(message: ResetDeviceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetDeviceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetDeviceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetDeviceRequest>): ResetDeviceRequest {
    return ResetDeviceRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResetDeviceRequest>): ResetDeviceRequest {
    const message = createBaseResetDeviceRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseResetDeviceResponse(): ResetDeviceResponse {
  return {};
}

export const ResetDeviceResponse: MessageFns<ResetDeviceResponse> = {
  encode(_: ResetDeviceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetDeviceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetDeviceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetDeviceResponse>): ResetDeviceResponse {
    return ResetDeviceResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ResetDeviceResponse>): ResetDeviceResponse {
    const message = createBaseResetDeviceResponse();
    return message;
  },
};

function createBaseAnalogAxisValue(): AnalogAxisValue {
  return { axisIndex: 0, adcChannel: 0, raw: 0, mv: 0, reportValue: 0, accumulatedDelta: 0 };
}

export const AnalogAxisValue: MessageFns<AnalogAxisValue> = {
  encode(message: AnalogAxisValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.axisIndex !== 0) {
      writer.uint32(8).uint32(message.axisIndex);
    }
    if (message.adcChannel !== 0) {
      writer.uint32(16).uint32(message.adcChannel);
    }
    if (message.raw !== 0) {
      writer.uint32(24).uint32(message.raw);
    }
    if (message.mv !== 0) {
      writer.uint32(32).int32(message.mv);
    }
    if (message.reportValue !== 0) {
      writer.uint32(40).int32(message.reportValue);
    }
    if (message.accumulatedDelta !== 0) {
      writer.uint32(48).int32(message.accumulatedDelta);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnalogAxisValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnalogAxisValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.axisIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.adcChannel = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.raw = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.mv = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.reportValue = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.accumulatedDelta = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AnalogAxisValue>): AnalogAxisValue {
    return AnalogAxisValue.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AnalogAxisValue>): AnalogAxisValue {
    const message = createBaseAnalogAxisValue();
    message.axisIndex = object.axisIndex ?? 0;
    message.adcChannel = object.adcChannel ?? 0;
    message.raw = object.raw ?? 0;
    message.mv = object.mv ?? 0;
    message.reportValue = object.reportValue ?? 0;
    message.accumulatedDelta = object.accumulatedDelta ?? 0;
    return message;
  },
};

function createBaseGetValuesRequest(): GetValuesRequest {
  return { id: 0 };
}

export const GetValuesRequest: MessageFns<GetValuesRequest> = {
  encode(message: GetValuesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetValuesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetValuesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetValuesRequest>): GetValuesRequest {
    return GetValuesRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetValuesRequest>): GetValuesRequest {
    const message = createBaseGetValuesRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseGetValuesResponse(): GetValuesResponse {
  return { values: [], sampledAtMs: 0 };
}

export const GetValuesResponse: MessageFns<GetValuesResponse> = {
  encode(message: GetValuesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.values) {
      AnalogAxisValue.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.sampledAtMs !== 0) {
      writer.uint32(16).uint32(message.sampledAtMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetValuesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetValuesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.values.push(AnalogAxisValue.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sampledAtMs = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetValuesResponse>): GetValuesResponse {
    return GetValuesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetValuesResponse>): GetValuesResponse {
    const message = createBaseGetValuesResponse();
    message.values = object.values?.map((e) => AnalogAxisValue.fromPartial(e)) || [];
    message.sampledAtMs = object.sampledAtMs ?? 0;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseRequest(): Request {
  return {
    listDevices: undefined,
    getDevice: undefined,
    setSamplingHz: undefined,
    setReportInterval: undefined,
    setAxisConfig: undefined,
    resetDevice: undefined,
    getValues: undefined,
  };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.listDevices !== undefined) {
      ListDevicesRequest.encode(message.listDevices, writer.uint32(10).fork()).join();
    }
    if (message.getDevice !== undefined) {
      GetDeviceRequest.encode(message.getDevice, writer.uint32(18).fork()).join();
    }
    if (message.setSamplingHz !== undefined) {
      SetSamplingHzRequest.encode(message.setSamplingHz, writer.uint32(26).fork()).join();
    }
    if (message.setReportInterval !== undefined) {
      SetReportIntervalRequest.encode(message.setReportInterval, writer.uint32(34).fork()).join();
    }
    if (message.setAxisConfig !== undefined) {
      SetAxisConfigRequest.encode(message.setAxisConfig, writer.uint32(42).fork()).join();
    }
    if (message.resetDevice !== undefined) {
      ResetDeviceRequest.encode(message.resetDevice, writer.uint32(50).fork()).join();
    }
    if (message.getValues !== undefined) {
      GetValuesRequest.encode(message.getValues, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.listDevices = ListDevicesRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getDevice = GetDeviceRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setSamplingHz = SetSamplingHzRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.setReportInterval = SetReportIntervalRequest.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.setAxisConfig = SetAxisConfigRequest.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.resetDevice = ResetDeviceRequest.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.getValues = GetValuesRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.listDevices = (object.listDevices !== undefined && object.listDevices !== null)
      ? ListDevicesRequest.fromPartial(object.listDevices)
      : undefined;
    message.getDevice = (object.getDevice !== undefined && object.getDevice !== null)
      ? GetDeviceRequest.fromPartial(object.getDevice)
      : undefined;
    message.setSamplingHz = (object.setSamplingHz !== undefined && object.setSamplingHz !== null)
      ? SetSamplingHzRequest.fromPartial(object.setSamplingHz)
      : undefined;
    message.setReportInterval = (object.setReportInterval !== undefined && object.setReportInterval !== null)
      ? SetReportIntervalRequest.fromPartial(object.setReportInterval)
      : undefined;
    message.setAxisConfig = (object.setAxisConfig !== undefined && object.setAxisConfig !== null)
      ? SetAxisConfigRequest.fromPartial(object.setAxisConfig)
      : undefined;
    message.resetDevice = (object.resetDevice !== undefined && object.resetDevice !== null)
      ? ResetDeviceRequest.fromPartial(object.resetDevice)
      : undefined;
    message.getValues = (object.getValues !== undefined && object.getValues !== null)
      ? GetValuesRequest.fromPartial(object.getValues)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    error: undefined,
    listDevices: undefined,
    getDevice: undefined,
    setSamplingHz: undefined,
    setReportInterval: undefined,
    setAxisConfig: undefined,
    resetDevice: undefined,
    getValues: undefined,
  };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.listDevices !== undefined) {
      ListDevicesResponse.encode(message.listDevices, writer.uint32(18).fork()).join();
    }
    if (message.getDevice !== undefined) {
      GetDeviceResponse.encode(message.getDevice, writer.uint32(26).fork()).join();
    }
    if (message.setSamplingHz !== undefined) {
      SetSamplingHzResponse.encode(message.setSamplingHz, writer.uint32(34).fork()).join();
    }
    if (message.setReportInterval !== undefined) {
      SetReportIntervalResponse.encode(message.setReportInterval, writer.uint32(42).fork()).join();
    }
    if (message.setAxisConfig !== undefined) {
      SetAxisConfigResponse.encode(message.setAxisConfig, writer.uint32(50).fork()).join();
    }
    if (message.resetDevice !== undefined) {
      ResetDeviceResponse.encode(message.resetDevice, writer.uint32(58).fork()).join();
    }
    if (message.getValues !== undefined) {
      GetValuesResponse.encode(message.getValues, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.listDevices = ListDevicesResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.getDevice = GetDeviceResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.setSamplingHz = SetSamplingHzResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.setReportInterval = SetReportIntervalResponse.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.setAxisConfig = SetAxisConfigResponse.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.resetDevice = ResetDeviceResponse.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.getValues = GetValuesResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.listDevices = (object.listDevices !== undefined && object.listDevices !== null)
      ? ListDevicesResponse.fromPartial(object.listDevices)
      : undefined;
    message.getDevice = (object.getDevice !== undefined && object.getDevice !== null)
      ? GetDeviceResponse.fromPartial(object.getDevice)
      : undefined;
    message.setSamplingHz = (object.setSamplingHz !== undefined && object.setSamplingHz !== null)
      ? SetSamplingHzResponse.fromPartial(object.setSamplingHz)
      : undefined;
    message.setReportInterval = (object.setReportInterval !== undefined && object.setReportInterval !== null)
      ? SetReportIntervalResponse.fromPartial(object.setReportInterval)
      : undefined;
    message.setAxisConfig = (object.setAxisConfig !== undefined && object.setAxisConfig !== null)
      ? SetAxisConfigResponse.fromPartial(object.setAxisConfig)
      : undefined;
    message.resetDevice = (object.resetDevice !== undefined && object.resetDevice !== null)
      ? ResetDeviceResponse.fromPartial(object.resetDevice)
      : undefined;
    message.getValues = (object.getValues !== undefined && object.getValues !== null)
      ? GetValuesResponse.fromPartial(object.getValues)
      : undefined;
    return message;
  },
};

function createBaseDeviceChangedNotification(): DeviceChangedNotification {
  return { device: undefined };
}

export const DeviceChangedNotification: MessageFns<DeviceChangedNotification> = {
  encode(message: DeviceChangedNotification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.device !== undefined) {
      AnalogInputDevice.encode(message.device, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceChangedNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceChangedNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.device = AnalogInputDevice.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeviceChangedNotification>): DeviceChangedNotification {
    return DeviceChangedNotification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeviceChangedNotification>): DeviceChangedNotification {
    const message = createBaseDeviceChangedNotification();
    message.device = (object.device !== undefined && object.device !== null)
      ? AnalogInputDevice.fromPartial(object.device)
      : undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { deviceChanged: undefined };
}

export const Notification: MessageFns<Notification> = {
  encode(message: Notification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceChanged !== undefined) {
      DeviceChangedNotification.encode(message.deviceChanged, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Notification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deviceChanged = DeviceChangedNotification.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Notification>): Notification {
    return Notification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Notification>): Notification {
    const message = createBaseNotification();
    message.deviceChanged = (object.deviceChanged !== undefined && object.deviceChanged !== null)
      ? DeviceChangedNotification.fromPartial(object.deviceChanged)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
