// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: zmk/runtime_input_processor/runtime_input_processor.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "zmk.runtime_input_processor";

/** Information about a single input processor */
export interface ProcessorInfo {
  /** Processor name (max 16 characters, short for BLE efficiency) */
  name: string;
  /** Current scale multiplier (for speed adjustment) */
  scaleMultiplier: number;
  /** Current scale divisor (for speed adjustment) */
  scaleDivisor: number;
  /** Current rotation in degrees */
  rotationDegrees: number;
}

/** Request to list all available input processors */
export interface ListProcessorsRequest {
}

export interface ListProcessorsResponse {
  processors: ProcessorInfo[];
}

/** Request to get settings for a specific processor */
export interface GetProcessorRequest {
  name: string;
}

export interface GetProcessorResponse {
  processor: ProcessorInfo | undefined;
}

/** Request to update scaling settings */
export interface SetScalingRequest {
  name: string;
  scaleMultiplier: number;
  scaleDivisor: number;
}

export interface SetScalingResponse {
  success: boolean;
}

/** Request to update rotation settings */
export interface SetRotationRequest {
  name: string;
  rotationDegrees: number;
}

export interface SetRotationResponse {
  success: boolean;
}

/** Main request message */
export interface Request {
  listProcessors?: ListProcessorsRequest | undefined;
  getProcessor?: GetProcessorRequest | undefined;
  setScaling?: SetScalingRequest | undefined;
  setRotation?: SetRotationRequest | undefined;
}

/** Error response */
export interface ErrorResponse {
  message: string;
}

/** Main response message */
export interface Response {
  error?: ErrorResponse | undefined;
  listProcessors?: ListProcessorsResponse | undefined;
  getProcessor?: GetProcessorResponse | undefined;
  setScaling?: SetScalingResponse | undefined;
  setRotation?: SetRotationResponse | undefined;
}

/** Notification when processor settings change */
export interface ProcessorSettingsNotification {
  processor: ProcessorInfo | undefined;
}

/** Notification wrapper */
export interface Notification {
  processorSettings?: ProcessorSettingsNotification | undefined;
}

function createBaseProcessorInfo(): ProcessorInfo {
  return { name: "", scaleMultiplier: 0, scaleDivisor: 0, rotationDegrees: 0 };
}

export const ProcessorInfo: MessageFns<ProcessorInfo> = {
  encode(message: ProcessorInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.scaleMultiplier !== 0) {
      writer.uint32(16).int32(message.scaleMultiplier);
    }
    if (message.scaleDivisor !== 0) {
      writer.uint32(24).int32(message.scaleDivisor);
    }
    if (message.rotationDegrees !== 0) {
      writer.uint32(32).int32(message.rotationDegrees);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessorInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessorInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.scaleMultiplier = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.scaleDivisor = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.rotationDegrees = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ProcessorInfo>): ProcessorInfo {
    return ProcessorInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessorInfo>): ProcessorInfo {
    const message = createBaseProcessorInfo();
    message.name = object.name ?? "";
    message.scaleMultiplier = object.scaleMultiplier ?? 0;
    message.scaleDivisor = object.scaleDivisor ?? 0;
    message.rotationDegrees = object.rotationDegrees ?? 0;
    return message;
  },
};

function createBaseListProcessorsRequest(): ListProcessorsRequest {
  return {};
}

export const ListProcessorsRequest: MessageFns<ListProcessorsRequest> = {
  encode(_: ListProcessorsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListProcessorsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListProcessorsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListProcessorsRequest>): ListProcessorsRequest {
    return ListProcessorsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListProcessorsRequest>): ListProcessorsRequest {
    const message = createBaseListProcessorsRequest();
    return message;
  },
};

function createBaseListProcessorsResponse(): ListProcessorsResponse {
  return { processors: [] };
}

export const ListProcessorsResponse: MessageFns<ListProcessorsResponse> = {
  encode(message: ListProcessorsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.processors) {
      ProcessorInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListProcessorsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListProcessorsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.processors.push(ProcessorInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListProcessorsResponse>): ListProcessorsResponse {
    return ListProcessorsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListProcessorsResponse>): ListProcessorsResponse {
    const message = createBaseListProcessorsResponse();
    message.processors = object.processors?.map((e) => ProcessorInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetProcessorRequest(): GetProcessorRequest {
  return { name: "" };
}

export const GetProcessorRequest: MessageFns<GetProcessorRequest> = {
  encode(message: GetProcessorRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetProcessorRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProcessorRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetProcessorRequest>): GetProcessorRequest {
    return GetProcessorRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetProcessorRequest>): GetProcessorRequest {
    const message = createBaseGetProcessorRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseGetProcessorResponse(): GetProcessorResponse {
  return { processor: undefined };
}

export const GetProcessorResponse: MessageFns<GetProcessorResponse> = {
  encode(message: GetProcessorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.processor !== undefined) {
      ProcessorInfo.encode(message.processor, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetProcessorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProcessorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.processor = ProcessorInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetProcessorResponse>): GetProcessorResponse {
    return GetProcessorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetProcessorResponse>): GetProcessorResponse {
    const message = createBaseGetProcessorResponse();
    message.processor = (object.processor !== undefined && object.processor !== null)
      ? ProcessorInfo.fromPartial(object.processor)
      : undefined;
    return message;
  },
};

function createBaseSetScalingRequest(): SetScalingRequest {
  return { name: "", scaleMultiplier: 0, scaleDivisor: 0 };
}

export const SetScalingRequest: MessageFns<SetScalingRequest> = {
  encode(message: SetScalingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.scaleMultiplier !== 0) {
      writer.uint32(16).int32(message.scaleMultiplier);
    }
    if (message.scaleDivisor !== 0) {
      writer.uint32(24).int32(message.scaleDivisor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetScalingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetScalingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.scaleMultiplier = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.scaleDivisor = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetScalingRequest>): SetScalingRequest {
    return SetScalingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetScalingRequest>): SetScalingRequest {
    const message = createBaseSetScalingRequest();
    message.name = object.name ?? "";
    message.scaleMultiplier = object.scaleMultiplier ?? 0;
    message.scaleDivisor = object.scaleDivisor ?? 0;
    return message;
  },
};

function createBaseSetScalingResponse(): SetScalingResponse {
  return { success: false };
}

export const SetScalingResponse: MessageFns<SetScalingResponse> = {
  encode(message: SetScalingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetScalingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetScalingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetScalingResponse>): SetScalingResponse {
    return SetScalingResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetScalingResponse>): SetScalingResponse {
    const message = createBaseSetScalingResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseSetRotationRequest(): SetRotationRequest {
  return { name: "", rotationDegrees: 0 };
}

export const SetRotationRequest: MessageFns<SetRotationRequest> = {
  encode(message: SetRotationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.rotationDegrees !== 0) {
      writer.uint32(16).int32(message.rotationDegrees);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetRotationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetRotationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.rotationDegrees = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetRotationRequest>): SetRotationRequest {
    return SetRotationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetRotationRequest>): SetRotationRequest {
    const message = createBaseSetRotationRequest();
    message.name = object.name ?? "";
    message.rotationDegrees = object.rotationDegrees ?? 0;
    return message;
  },
};

function createBaseSetRotationResponse(): SetRotationResponse {
  return { success: false };
}

export const SetRotationResponse: MessageFns<SetRotationResponse> = {
  encode(message: SetRotationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetRotationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetRotationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetRotationResponse>): SetRotationResponse {
    return SetRotationResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetRotationResponse>): SetRotationResponse {
    const message = createBaseSetRotationResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseRequest(): Request {
  return { listProcessors: undefined, getProcessor: undefined, setScaling: undefined, setRotation: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.listProcessors !== undefined) {
      ListProcessorsRequest.encode(message.listProcessors, writer.uint32(10).fork()).join();
    }
    if (message.getProcessor !== undefined) {
      GetProcessorRequest.encode(message.getProcessor, writer.uint32(18).fork()).join();
    }
    if (message.setScaling !== undefined) {
      SetScalingRequest.encode(message.setScaling, writer.uint32(26).fork()).join();
    }
    if (message.setRotation !== undefined) {
      SetRotationRequest.encode(message.setRotation, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.listProcessors = ListProcessorsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getProcessor = GetProcessorRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setScaling = SetScalingRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.setRotation = SetRotationRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.listProcessors = (object.listProcessors !== undefined && object.listProcessors !== null)
      ? ListProcessorsRequest.fromPartial(object.listProcessors)
      : undefined;
    message.getProcessor = (object.getProcessor !== undefined && object.getProcessor !== null)
      ? GetProcessorRequest.fromPartial(object.getProcessor)
      : undefined;
    message.setScaling = (object.setScaling !== undefined && object.setScaling !== null)
      ? SetScalingRequest.fromPartial(object.setScaling)
      : undefined;
    message.setRotation = (object.setRotation !== undefined && object.setRotation !== null)
      ? SetRotationRequest.fromPartial(object.setRotation)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    error: undefined,
    listProcessors: undefined,
    getProcessor: undefined,
    setScaling: undefined,
    setRotation: undefined,
  };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.listProcessors !== undefined) {
      ListProcessorsResponse.encode(message.listProcessors, writer.uint32(18).fork()).join();
    }
    if (message.getProcessor !== undefined) {
      GetProcessorResponse.encode(message.getProcessor, writer.uint32(26).fork()).join();
    }
    if (message.setScaling !== undefined) {
      SetScalingResponse.encode(message.setScaling, writer.uint32(34).fork()).join();
    }
    if (message.setRotation !== undefined) {
      SetRotationResponse.encode(message.setRotation, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.listProcessors = ListProcessorsResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.getProcessor = GetProcessorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.setScaling = SetScalingResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.setRotation = SetRotationResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.listProcessors = (object.listProcessors !== undefined && object.listProcessors !== null)
      ? ListProcessorsResponse.fromPartial(object.listProcessors)
      : undefined;
    message.getProcessor = (object.getProcessor !== undefined && object.getProcessor !== null)
      ? GetProcessorResponse.fromPartial(object.getProcessor)
      : undefined;
    message.setScaling = (object.setScaling !== undefined && object.setScaling !== null)
      ? SetScalingResponse.fromPartial(object.setScaling)
      : undefined;
    message.setRotation = (object.setRotation !== undefined && object.setRotation !== null)
      ? SetRotationResponse.fromPartial(object.setRotation)
      : undefined;
    return message;
  },
};

function createBaseProcessorSettingsNotification(): ProcessorSettingsNotification {
  return { processor: undefined };
}

export const ProcessorSettingsNotification: MessageFns<ProcessorSettingsNotification> = {
  encode(message: ProcessorSettingsNotification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.processor !== undefined) {
      ProcessorInfo.encode(message.processor, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessorSettingsNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessorSettingsNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.processor = ProcessorInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ProcessorSettingsNotification>): ProcessorSettingsNotification {
    return ProcessorSettingsNotification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessorSettingsNotification>): ProcessorSettingsNotification {
    const message = createBaseProcessorSettingsNotification();
    message.processor = (object.processor !== undefined && object.processor !== null)
      ? ProcessorInfo.fromPartial(object.processor)
      : undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { processorSettings: undefined };
}

export const Notification: MessageFns<Notification> = {
  encode(message: Notification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.processorSettings !== undefined) {
      ProcessorSettingsNotification.encode(message.processorSettings, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Notification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.processorSettings = ProcessorSettingsNotification.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Notification>): Notification {
    return Notification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Notification>): Notification {
    const message = createBaseNotification();
    message.processorSettings = (object.processorSettings !== undefined && object.processorSettings !== null)
      ? ProcessorSettingsNotification.fromPartial(object.processorSettings)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
